name: 🔍 Verify Environment Variables

on:
  workflow_dispatch:

jobs:
  verify-secrets:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v4
      
    - name: 🔍 Check Environment Variables
      env:
        NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
        NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
      run: |
        echo "🔍 Checking environment variables..."
        
        if [ -n "$NOTION_API_KEY" ]; then
          echo "✅ NOTION_API_KEY is set (length: ${#NOTION_API_KEY})"
          echo "   First 10 chars: ${NOTION_API_KEY:0:10}..."
        else
          echo "❌ NOTION_API_KEY is not set"
        fi
        
        if [ -n "$NOTION_DATABASE_ID" ]; then
          echo "✅ NOTION_DATABASE_ID is set (length: ${#NOTION_DATABASE_ID})"
          echo "   Value: $NOTION_DATABASE_ID"
        else
          echo "❌ NOTION_DATABASE_ID is not set"
        fi
        
        echo ""
        echo "🎯 Environment verification complete"
        
    - name: 🐍 Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: 📦 Install minimal dependencies
      run: |
        pip install notion-client requests
        
    - name: 🔗 Test Notion API Connection
      env:
        NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
        NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
      run: |
        python3 << 'EOF'
        import os
        import sys
        from notion_client import Client
        
        try:
            # Initialize Notion client
            notion_api_key = os.environ.get('NOTION_API_KEY')
            notion_database_id = os.environ.get('NOTION_DATABASE_ID')
            
            if not notion_api_key:
                print("❌ NOTION_API_KEY not found in environment")
                sys.exit(1)
                
            if not notion_database_id:
                print("❌ NOTION_DATABASE_ID not found in environment")
                sys.exit(1)
            
            print(f"🔍 Testing connection with API key: {notion_api_key[:10]}...")
            
            client = Client(auth=notion_api_key)
            
            # Test 1: Get user info
            me = client.users.me()
            print(f"✅ Connected as: {me['name']}")
            
            # Test 2: Try to access the database/page
            try:
                db_info = client.databases.retrieve(notion_database_id)
                print(f"✅ Database access successful: {db_info['title'][0]['plain_text']}")
                print("🎯 Notion integration is working properly!")
            except Exception as db_error:
                # Might be a page ID instead of database ID
                try:
                    page_info = client.pages.retrieve(notion_database_id)
                    print(f"✅ Page access successful: {page_info['properties']}")
                    print("🎯 Notion integration is working properly!")
                except Exception as page_error:
                    print(f"⚠️  Access test failed: {db_error}")
                    print("ℹ️  This might be expected if database/page permissions are not set")
                    
        except Exception as e:
            print(f"❌ Connection failed: {e}")
            sys.exit(1)
        EOF